//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.3.2.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using Example_Model.Screens.Fahrplan;

namespace Example_Model
{
    [SoftwareModel]
    public partial class ExampleApp : IAppBasics
    {
        partial void InitScreens()
        {
            Auswahl = new Auswahl(this);
            Kauf = new Kauf(this);
            Final = new Final(this);
        }


        public Auswahl Auswahl { get; set; }
        
        public Kauf Kauf { get; set; }
        
        public Final Final { get; set; }
        
    }
}