//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.3.2.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Example;

namespace Example_Model.Screens.Fahrplan
{
    [Screen]
    public partial class Auswahl : Progile.TRIO.BaseModel.BaseScreen
    {
        public Auswahl(ExampleApp app) : base(app, @"Auswahl", Images.Fahrplan.Auswahl.Screen_Loaded)
        {
            App = app;
            Von = new Progile.TRIO.BaseModel.TextBox(appBasics: AppBasics, displayName: "Von", searchText: "Von", filters: ScreenSelect) { ParentElement = this };
            Nach = new Progile.TRIO.BaseModel.TextBox(appBasics: AppBasics, displayName: "Nach", searchText: "Nach", filters: ScreenSelect) { ParentElement = this };
            Uhrzeit = new Progile.TRIO.BaseModel.TextBox(appBasics: AppBasics, displayName: "Uhrzeit", searchText: "Uhrzeit", filters: ScreenSelect) { ParentElement = this };
            Züge = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Züge", activeImageReference: Images.Fahrplan.Auswahl.Züge.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private ExampleApp App { get; set; }
        public Progile.TRIO.BaseModel.TextBox Von { get; private set; }

        public Progile.TRIO.BaseModel.TextBox Nach { get; private set; }

        public Progile.TRIO.BaseModel.TextBox Uhrzeit { get; private set; }

        public Progile.TRIO.BaseModel.Button Züge { get; private set; }

        partial void ConfigureElementProperties();
    }
}