//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.3.2.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Example;

namespace Example_Model.Screens.Fahrplan
{
    [Screen]
    public partial class Final : Progile.TRIO.BaseModel.BaseScreen
    {
        public Final(ExampleApp app) : base(app, @"Final", Images.Fahrplan.Final.Screen_Loaded)
        {
            App = app;
            Zug1Label = new Progile.TRIO.BaseModel.Label(tester: t, displayName: "Zug 1 Label", imageReference: Images.Fahrplan.Final.Zug1Label, filters: ScreenSelect) { ParentElement = this };
            Zurück = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Zurück", searchText: "< Zurück", useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            Zug2Label = new Progile.TRIO.BaseModel.Label(tester: t, displayName: "Zug 2 Label", imageReference: Images.Fahrplan.Final.Zug2Label, filters: ScreenSelect) { ParentElement = this };
            Zug3Label = new Progile.TRIO.BaseModel.Label(tester: t, displayName: "Zug 3 Label", imageReference: Images.Fahrplan.Final.Zug3Label, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private ExampleApp App { get; set; }
        public Progile.TRIO.BaseModel.Label Zug1Label { get; private set; }

        public Progile.TRIO.BaseModel.Button Zurück { get; private set; }

        public Progile.TRIO.BaseModel.Label Zug2Label { get; private set; }

        public Progile.TRIO.BaseModel.Label Zug3Label { get; private set; }

        partial void ConfigureElementProperties();
    }
}