//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.3.2.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Example;

namespace Example_Model.Screens.Fahrplan
{
    [Screen]
    public partial class Kauf : Progile.TRIO.BaseModel.BaseScreen
    {
        public Kauf(ExampleApp app) : base(app, @"Kauf", Images.Fahrplan.Kauf.Screen_Loaded)
        {
            App = app;
            Zurück = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Zurück", searchText: "Zurück", useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            Zug1Abfahrt = new Progile.TRIO.BaseModel.Label(tester: t, displayName: "Zug 1 Abfahrt", searchText: "Abfahrt 10:55", filters: ScreenSelect) { ParentElement = this };
            Tickets1 = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Tickets 1", searchText: "Tickets", useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            Zug2Abfahrt = new Progile.TRIO.BaseModel.Label(tester: t, displayName: "Zug 2 Abfahrt", searchText: "Abfahrt 11:25", filters: ScreenSelect) { ParentElement = this };
            Tickets2 = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Tickets 2", searchText: "Tickets", useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            Zug3Abfahrt = new Progile.TRIO.BaseModel.Label(tester: t, displayName: "Zug 3 Abfahrt", searchText: "Abfahrt 11:43", filters: ScreenSelect) { ParentElement = this };
            Tickets3 = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Tickets 3", searchText: "Tickets", useVisualSense: false, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private ExampleApp App { get; set; }
        public Progile.TRIO.BaseModel.Button Zurück { get; private set; }

        public Progile.TRIO.BaseModel.Label Zug1Abfahrt { get; private set; }

        public Progile.TRIO.BaseModel.Button Tickets1 { get; private set; }

        public Progile.TRIO.BaseModel.Label Zug2Abfahrt { get; private set; }

        public Progile.TRIO.BaseModel.Button Tickets2 { get; private set; }

        public Progile.TRIO.BaseModel.Label Zug3Abfahrt { get; private set; }

        public Progile.TRIO.BaseModel.Button Tickets3 { get; private set; }

        partial void ConfigureElementProperties();
    }
}